### PR TITLE
Basic Modifications to IP Asset Registry register

### PR DESCRIPTION
**Pull request by jdubpark**
- Remove check for `IERC721` interface support since we check for`IERC721Metadata` interface support, which inherits IERC721.
- Remove chainId from naming since contracts and offchain apps can already know the chain an IP is on.

### CODE REVIEW

**Comment by kingster-will** [comment]
> Remove chainId from naming since contracts and offchain apps can already know the chain an IP is on.

For cross-chain scenarios, the offchain app might NOT be able to directly to know the original chain of an IP.

**Comment by jdubpark** [comment]
> For cross-chain scenarios, the offchain app might NOT be able to directly to know the original chain of an IP.

Using onchain name as a reference is not ideal as the underlying NFTs can be multi-chain as well, such as y00ts or DeGods migrating chains.

I agree that providing clarity is nice but I don't see IP's name as a good place for clarity.

**Comment by jdubpark** [comment]
Will just keep Chain ID for potential offchain usage, but at the cost of gas overhead to store extra string.

**Comment by LeoHChen** [comment]
> Will just keep Chain ID for potential offchain usage, but at the cost of gas overhead to store extra string.

maybe remove the id from the name for local chain registration, and add id for cross-chain registration?

**Pull request closed without merging**
